version: "3.9"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: dividends
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

  api:
    build: ./app
    volumes:
      - ./app:/app
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/dividends

volumes:
  postgres_data:
