services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: dividends
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

  api:
    build: ./app
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:password@db:5432/dividends
    ports:
      - "8000:8000"

  ui:
    build: ./app
    command: uvicorn ui:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - ./app:/app
    depends_on:
      - api
    ports:
      - "8001:8001"

volumes:
  postgres_data:
